// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var Forge, iced, __iced_k, __iced_k_noop;

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  exports.Forge = Forge = (function() {
    function Forge(_arg) {
      this.chain = _arg.chain;
    }

    Forge.prototype.forge = function(cb) {
      var err, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/node-test-sigchain/src/forge.iced",
            funcname: "Forge.forge"
          });
          _this.chain.output(JSON.stringify(_this.chain.get_data()), __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return err = arguments[0];
              };
            })(),
            lineno: 9
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          return cb(err);
        };
      })(this));
    };

    return Forge;

  })();

}).call(this);
