// Generated by IcedCoffeeScript 108.0.13
(function() {
  var copy_obj;

  exports.copy_obj = copy_obj = function(o) {
    var e, k, tmp, v, _i, _len, _results;
    if ((o == null) || (typeof o !== 'object')) {
      return o;
    } else if (Array.isArray(o)) {
      _results = [];
      for (_i = 0, _len = o.length; _i < _len; _i++) {
        e = o[_i];
        _results.push(copy_obj(e));
      }
      return _results;
    } else if (Buffer.isBuffer(o)) {
      return Buffer.concat([o]);
    } else {
      tmp = {};
      for (k in o) {
        v = o[k];
        tmp[k] = copy_obj(v);
      }
      return tmp;
    }
  };

}).call(this);
